title: Helena Yang
#author:
#  name: Helena Yang
email: hfy@andrew.cmu.edu
#description: >
#  CMU SCS '24 | she/her

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  heleaf
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: leafcat26
    linkedin: helenafyang
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - art.markdown
 - programming.markdown
 - blog.markdown
#  - tanims23.markdown
# - games.markdown
# - papers.markdown

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
 programming:
  output: true
 art:
  output: true
 misc:
  output: true
 posts:
   output: true
 tanim:
    output: true

include:
 - "image-gallery.html"
   #- "profile.png"
   # - "hfy_resume.pdf"

imagesurl: "/img/"
thumbsurl: "/thumbs/"
 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
