title: Helena Yang
author:
  name: Helena Yang
  email: hfy@andrew.cmu.edu
#description: > # this means to ignore newlines until "show_excerpts:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  heleaf
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: leaf.rat
    linkedin: helenafyang
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - programming.markdown
 - games.markdown
 - art.markdown
 - papers.markdown

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
 programming:
  output: true
 games:
  output: true
 art:
  output: true
 papers:
  output: true
 misc:
  output: true

include:
 - "image-gallery.html"
 - "profile.png"
 - "hfy_resume.pdf"

imagesurl: "/img/"
thumbsurl: "/thumbs/"
 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
